name: Publish release on Docker Hub

on:
  push:
    tags: 
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run tests
        run: go test .

  build:
    needs: [test]
    runs-on: ubuntu-latest

    env:
      IMAGE: wichert/k8s-sentry

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build Docker image
        run: |
          docker build --tag $IMAGE .
      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Docker image
        run: |
          version=$(echo $GITHUB_REF | cut -d/ -f3)
          docker push $IMAGE
          docker tag $IMAGE $IMAGE:$version
          docker push $IMAGE:$version

      - name: Generate changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false

